[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

# Redirects to fix React Router 404 issue
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  CI = "false"
